### ISSUE TITLE
can you help me with this error？

### ISSUE THREAD

**Issue by xianjunjia** [abhishek-ram/django-pyas2#1]
Request Method: | POST
-- | --
http://127.0.0.1:8000/pyas2/as2send/?partner_id=CDETEST
2.1
AttributeError
'PublicKeyInfo' object has no attribute 'keys'
D:\Anaconda3\lib\site-packages\asn1crypto\core.py in __init__, line 3067
D:\Anaconda3\python.exe
3.6.3
['D:\\PycharmProjects\\django-pyas2-master',  'D:\\Anaconda3\\python36.zip',  'D:\\Anaconda3\\DLLs',  'D:\\Anaconda3\\lib',  'D:\\Anaconda3',  'D:\\Anaconda3\\lib\\site-packages',  'D:\\Anaconda3\\lib\\site-packages\\Babel-2.5.0-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\django_pyas2-1.0.0b2-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\pyas2lib-1.0.3-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\pyopenssl-17.5.0-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\oscrypto-0.19.1-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\asn1crypto-0.24.0-py3.6.egg',  'D:\\Anaconda3\\lib\\site-packages\\cryptography-2.3.1-py3.6-win-amd64.egg',  'D:\\Anaconda3\\lib\\site-packages\\win32',  'D:\\Anaconda3\\lib\\site-packages\\win32\\lib',  'D:\\Anaconda3\\lib\\site-packages\\Pythonwin']
Wed, 3 Oct 2018 10:10:07 +0000

**Comment by xianjunjia** [comment]
> Can you explain what you are trying to do and BTW this library is not yet production ready....

i am trying to use this project sending AS2 message to my partner，after run the scrip“python setup.py install”

**Comment by abhishek-ram** [comment]
Go ahead and use this library https://pyas2.readthedocs.io/en/latest/

**Comment by xianjunjia** [comment]
> Go ahead and use this library https://pyas2.readthedocs.io/en/latest/

thanks for your reply. i am not major in computer science，just interested in AS2 protocol.

**Comment by abhishek-ram** [comment]
Okay can you tell me what steps you followed so that I can replicate the error
