### ISSUE TITLE
manageas2server --retry doesn't work

### ISSUE THREAD

**Issue by User-26** [abhishek-ram/django-pyas2#102]
Hello! Steps to reproduce:

1. Send "message-1.txt": "manage.py sendas2message AS2.P-1 AS2.P-2 message-1.txt"
2. Stop AS2.P-2 server
3. Send "message-2.txt" : "manage.py sendas2message AS2.P-1 AS2.P-2 message-2.txt"
4. Start AS2.P-2 server
5. Resend "message-2.txt": "manage.py manageas2server --retry" 

Expected results:
message-1.txt delivered successfully
message-2.txt delivered successfully after retransmission

Actual results:
message-1.txt delivered successfully
message-2.txt is not delivered

**Comment by abhishek-ram** [comment]
What is the error, can you please share it

**Comment by User-26** [comment]
Installed django-pyas2 version 1.2.3. Retransmission works fine. Thanks!
