### ISSUE TITLE
unsupported operand type(s) for +: 'NoneType' and 'bytes' trying to add public certificate

### ISSUE THREAD

**Issue by jolsen71** [abhishek-ram/django-pyas2#16]
I've just installed the new django-pyas2 project and I'm attempting to configure it for the first time. When I attempt to install a public certificate and ca file currently in use by the older pyas2 project, I get the following error:

```
TypeError at /admin/pyas2/publiccertificate/add/
unsupported operand type(s) for +: 'NoneType' and 'bytes'

Request Method:	POST
Request URL:	http://as2-dev.kwikee.com/admin/pyas2/publiccertificate/add/
Django Version:	2.2.2
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +: 'NoneType' and 'bytes'
Exception Location:	/projects/as2/env/lib/python3.6/site-packages/oscrypto/keys.py in _unarmor_pem_openssl_private, line 397
Python Executable:	/usr/local/bin/python3
Python Version:	3.6.8
Python Path:	
['/raid/0/www/docs/projects/as2',
 '/raid/0/www/docs/projects/as2/env/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6',
 '/usr/local/lib/python36.zip',
 '/usr/local/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/site-packages']
Server time:	Wed, 3 Jul 2019 10:06:26 -0500
```

I'm using the latest package available via pip, which is 1.1.1 and I used a .pem certificate file and a .der CA file. It doesn't seem to matter if I select "verify certificate" or not. 

pyOpenSSL==17.5.0
OpenSSL 1.0.2h  

Please advise.

**Comment by abhishek-ram** [comment]
Is it possible to email me the certs so that I can replicate the issue?

**Comment by jolsen71** [comment]
I had a hard drive failure and lost the instance of the project. I have not been able to recreate it, so I going to close this issue. Thank  you
