### ISSUE TITLE
Cannot exchange encrypted data with some AS2 solutions: missing signature.

### ISSUE THREAD

**Issue by chadgates** [abhishek-ram/django-pyas2#5]
Problem with sending AS2 messages to solution like rssbus. 
With rssbus, cannot send messages anymore and error "[2019-05-29T10:35:37] [Error] [ReceiveFile - TestAS2] Error: A signature was expected and not provided." is thrown if signature is mandatory. (LoggingExample.zip)
When requirements for signature is removed, it seems the file is received but the file is the Mime instead of the file.  (attachment AS21.zip) 

In pyas2, sending as base64 (did not try updated version with binary content), the exchange had no problems. 

[LoggingExample.zip](https://github.com/abhishek-ram/django-pyas2/files/3231711/LoggingExample.zip)
[AS21.zip](https://github.com/abhishek-ram/django-pyas2/files/3231712/AS21.zip)

**Comment by abhishek-ram** [comment]
We could give the option of encoding as base64 or binary but first we need to make sure that is the issue. Can you try switching to base 64 and see what happens?

**Comment by chadgates** [comment]
Have "reverted" changes in pyas2lib.as2 and pyas2lib.utils to version 1.0.4 (everything that was "binary"), and messages were processed afterwards correctly by rssbus as well AxWay B2Bi. 

Both of these systems could not identify that there was a signature in the the content submitted, so suggest to reimplement non-binary transfer as default and make binary optional in the pyas2lib.

**Comment by abhishek-ram** [comment]
Great, i will make updates to make this configurable at the partner level. But it will be binary that is default as it takes up less space.

**Comment by chadgates** [comment]
Have looked into this further and realized it was not a problem with binary particularly, but with the ay pyas2lib is replacing line endings. The testfile has line endings with "\n" only, which ByteGenerator uses by default. However, if the incoming file actually has ”\r\n", then the signature will be invalid causing all kinds of issues. 
I am updating the pullrequest on pyas2lib to that will also fix this issues.

**Comment by abhishek-ram** [comment]
@chadgates the signatures were always and still send as base64... Do you mean that encrypted data needs to be sent as base64 instead of binary?

**Comment by chadgates** [comment]
@abhishek-ram : If https://github.com/abhishek-ram/pyas2-lib/pull/9 is accepted/merged , this issue is closed for me. Route cause was not "binary" but the signatures that were not consistently working in version 1.1 .

**Comment by abhishek-ram** [comment]
Handled in v1.1.0. @chadgates we now use the new version of pyas2lib. Thanks for you work on this, the solution is much cleaner now.
