### ISSUE TITLE
Add original filename to messages and enable search

### ISSUE THREAD

**Issue by chadgates** [abhishek-ram/django-pyas2#6]
As with previous version, suggest to add filename back to messages and allow filtering/searching by filename.

**Comment by abhishek-ram** [comment]
Hmmm searching will always be based on message Ids in AS2.

**Comment by chadgates** [comment]
The idea here is that one might not know the message id yet. Like when BOTS generates an outgoing file that needs to be sent via AS2. One knows the filename from BOTS and needs to determine the message id in AS2. There is no way of doing that without the filename.

**Comment by abhishek-ram** [comment]
Yes I see your point let me see if I can add this.

**Comment by abhishek-ram** [comment]
Handled in v1.1.0
