### ISSUE TITLE
Progress log for messages - bring back from pyas2 ? 

### ISSUE THREAD

**Issue by chadgates** [abhishek-ram/django-pyas2#69]
I do found the logging information useful that existed in pyas2. Is there a particular reason that this functionality did not make it into django-pyas2 or should we work on bringing it back in some form ?  

<img width="1114" alt="pyas2_log" src="https://user-images.githubusercontent.com/11510951/152543535-ca4a1b1f-2413-4d25-81df-2d7e8220da89.png">

**Comment by abhishek-ram** [comment]
I thought it was not useful, i mean all you need to know is if the message was sent successfully or not and if it failed what was the reason it failed.

**Comment by chadgates** [comment]
In some cases, the reason was not clear to me. "Failed to parse AS2 message" and "Failed to parse AS2 MDN" exceptions are hard to determine what actually went wrong. But I do get your point and probably the logs won't help in such cases either.

**Comment by abhishek-ram** [comment]
Yes, those error messages are not useful. We do store tracebacks as well in some places, we just need to make sure that we are doing it everywhere.
