### ISSUE TITLE
Do we have REST API reference for pyAS2 Django Server?

### ISSUE THREAD

**Issue by Arun-V-S** [abhishek-ram/django-pyas2#72]
Do we have REST API reference for pyAS2 Django Server?

I see in the logs, API is been hit. 
Some of them that I found in logs, like
GET /admin/pyas2/publiccertificate/add/ HTTP/1.1
POST /admin/pyas2/partner/<partnerOrgName>/change/ 

Can I get that full list of REST API reference to add/view/delete public certs, private certs, partner, organisation, send message etc.

Is there any way to pull out that information? Thanks in advance

**Comment by abhishek-ram** [comment]
We have not added any rest APIs for this project.

**Comment by Arun-V-S** [comment]
Closing this issue. Thanks
