### ISSUE TITLE
Encrypted File

### ISSUE THREAD

**Issue by AvatarBhola** [abhishek-ram/django-pyas2#79]
I am unable to see the EDI documents encrypted from my end. I need to have a record of the file being encrypted.

**Comment by abhishek-ram** [comment]
What exactly do you mean by that?

**Comment by AvatarBhola** [comment]
I want to see the raw encrypted file. I am only able to see the mdn messages and the messages I see in inbox are not encrypted.

**Comment by abhishek-ram** [comment]
AS2 is about transport layer encryption and not at rest, you will need to handle the encryption in this case

**Comment by AvatarBhola** [comment]
How would I do that?
