### ISSUE TITLE
Handling of duplicate messages in case first transmission had an error.

### ISSUE THREAD

**Issue by chadgates** [abhishek-ram/django-pyas2#8]
When file is transferred and an error happens in processing, an MDN is triggered to the sender, stating that there was an error. Therefore the partner will resend the message. 
However, when the partner resends, the new message is considered a "duplicate". 

Shouldn't duplicate check check for successful messages only? Currently it seems it applies to all messages, irrespective of their status. Suggest to add the status to the filter criteria. 
 
example of processing error, that seems to happen under some circumstances that I could not yet identify, usually around the time when a new folder was created, but it does not always happen on the first one: 
```
An error occurred during the AS2 message processing: [Errno 17] File exists '/data/messages/__store/payload/received/20190530'
```

**Comment by abhishek-ram** [comment]
A duplicate message occurs only when there are issues in case of transmission. In other cases it should not happen and message should be resent with a new ID.

The issue you are talking about is a bug and should be considered as a valid scenario.

**Comment by abhishek-ram** [comment]
This issue has been fixed in later versions of django https://code.djangoproject.com/ticket/29890.

Should we just increase the django version in requirements

**Comment by chadgates** [comment]
@abhishek-ram: Yes, I would suggest 2.2 (being LTS). 
I do have the problem on the previous version, still running on Python 2.7, so once I can migrate (currently the "binary"-issue is blocking my migration) I can monitor if that issue still happens.

**Comment by abhishek-ram** [comment]
Hmm so this issue was on the old pyas2?

**Comment by chadgates** [comment]
Yes.

**Comment by abhishek-ram** [comment]
Handled in v1.1.0
