### ISSUE TITLE
X-Content-Type-Options header Error: nosniff

### ISSUE THREAD

**Issue by AvatarBhola** [abhishek-ram/django-pyas2#90]
Customer asked to stop sending the X-Content-Type-Options header or any other non-compliant headers in the AS2 MDN.
See this link : https://www.ibm.com/support/pages/node/294385
Can we disable this param when sending the MDN reciept.
Thanks,

**Comment by chadgates** [comment]
@AvatarBhola : this is a django setting. You should put in your settings.py following: 
SECURE_CONTENT_TYPE_NOSNIFF = False

Also see:
# https://docs.djangoproject.com/en/2.2/ref/settings/#secure-content-type-nosniff

**Comment by AvatarBhola** [comment]
Thank you! this resolved this part of the issue.
